# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #strategy:
    #  matrix:
    #    java: [ 8, 11 ]
    #name: Istio Java ${{ matrix.java }} API

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 8


    - name: KinD (Kubernetes in Docker) Action
      uses: engineerd/setup-kind@v0.3.0
      with:
        version: v0.8.0

    - name: Kubernetes CLI - kubectl
      uses: steebchen/kubectl@v1.0.0

    - run: |
        cd $GITHUB_WORKSPACE
        istioVersion=$(make istio_version)
        mkdir install && cd install
        kind create cluster --name istio-testing
        kubectl config use-context kind-istio-testing
        kubectl config set-context --current --namespace=default
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION="${istioVersion}" sh -
        ./"istio-${istioVersion}"/bin/istioctl manifest apply --set profile=minimal
        cd ..
        ./mvnw clean install -Pit -Dhttp2.disable=true
